### PR TITLE
Fix connections over dns.loxonecloud.com

### PR DESCRIPTION
**Pull request by 07pepa**
* fixed failing connection over loxoncecloud
* simplified redirection logic
* simplified url setup
* fix __main__.py
* fixed typos
* improved typing

### CODE REVIEW

**Comment by JoDehli** [comment]
I tried your changes. The host and the port must be still available. And the URL should be configurable via GUI. For me it doesn't work. The gen1 need to be configurable via host and port. And also all old configuration should still be valid. If the changes are not backward compatible I get a lot of questions from users. 

Can you try to fix it?

**Comment by JoDehli** [comment]
@07pepa 
I added a migration from the old host and port config to the new url based config. I think it is still working. At least for me now with a gen1 and local connection it is still working. If you can confirm that with your external connection i will merge it.

**Comment by 07pepa** [comment]
it works only websocket does not work from outside... but i thing that is normal

**Comment by JoDehli** [comment]
@07pepa what do you mean with websocket? The hole communication is done via websocket. Or did I understand something wrong.

**Comment by 07pepa** [comment]
> @07pepa what do you mean with websocket? The hole communication is done via websocket. Or did I understand something wrong.

Well JSON downloading works... And since we socket should work same... It should work but doesn't... Locally it works however

**Pull request merged**
